name: flutter_utils
description: Flutter Utils.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  validators: ^3.0.0
  shared_preferences: ^2.0.15
  timer_count_down: ^2.2.1
  firebase_core: ^2.4.0
  cloud_firestore: ^4.3.0
  permission_handler: ^10.2.0
  http: ^0.13.5
  fluttertoast: ^8.1.2
  flutter_smart_dialog: ^4.8.0
  firebase_database: ^10.0.9
  video_player: ^2.4.10
  link_preview_generator: ^1.2.0
  share: ^2.0.4
  image_picker: ^0.8.6
  google_fonts: ^3.0.1
  photo_view: ^0.14.0
  equatable: ^2.0.5
  substring_highlight: ^1.0.33
#  flutter_remote_icon: ^0.0.3+6
  flutter_svg: ^2.0.0+1
  intl_phone_field: ^3.1.0
  pod_player: ^0.1.0
  connectivity_plus: ^3.0.3
  firebase_storage: ^11.0.16
  intl: ^0.17.0
  badges: ^3.0.2
  camera: ^0.10.3+2
  cached_network_image: ^3.2.3
  lottie: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/png_icons/
    - assets/images/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
